name: Setup
description: Downloads Pnpm, node, and setups cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile

    - name: Git config
      shell: bash
      run: |
        git config user.email "javi.igl.gar@gmail.com"
        git config user.name "GitHub Bot"
