#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-10-30"
name = "unicornify-web-pre"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "unicornify-web"
database_id = "c0913b0f-6bcc-4990-a01d-06491bfb828e"
migrations_dir = "migrations"
